feat: headers components
devcodapp/design-system pull request #2
Opened 2023-11-24 14:32 UTC by Anderson22-dev

Criação dos componentes dos headers

2023-11-29 23:05 UTC, Eduardo-BarrosoS requested changes
You should create accordion in another branch

2023-11-30 18:19 UTC, qalexandre commented
@Anderson22-dev  faça um pull da develop primeiro, resolva os conflitos e sobe as alterações

2023-12-01 14:22 UTC, Eduardo-BarrosoS requested changes

2023-12-01 14:22 UTC, Eduardo-BarrosoS commented on package.json
> +    "dependencies": {
Replace fontawesome to lucide react lib

2023-12-01 14:22 UTC, Eduardo-BarrosoS commented on src/app/page.tsx
If you are not using Text component, you can delete this one

2023-12-01 14:22 UTC, Eduardo-BarrosoS commented on src/app/page.tsx
If you are not using React import, you can delete this one

2023-12-01 14:22 UTC, Eduardo-BarrosoS commented on src/components/Header.tsx
> +    <div className="flex flex-row items-center">
![image](https://github.com/devcodapp/design-system/assets/75212547/79c60abd-7015-4e00-b97c-a1318bbefc00)

You need to add a space between buttons

2023-12-05 23:53 UTC, Eduardo-BarrosoS requested changes

2023-12-05 23:53 UTC, Eduardo-BarrosoS commented on tailwind.config.ts
> +  plugins: [nextui()],
Are you sure you need this plugin and why?

2023-12-05 23:53 UTC, Eduardo-BarrosoS commented on src/components/Header.tsx
> +
You have to develop pixel perfect what is on figma design.
It means that this component should be responsive.

2023-12-15 12:51 UTC, Eduardo-BarrosoS commented
> You should create accordion in another branch

2023-12-15 12:54 UTC, Eduardo-BarrosoS approved these changes
Approved

2023-12-15 13:00 UTC, merged