feature: Dialog
devcodapp/design-system pull request #6
Opened 2023-11-30 03:11 UTC by andrebellico

2023-11-30 18:21 UTC, qalexandre approved these changes

2023-12-04 14:56 UTC, Eduardo-BarrosoS requested changes

2023-12-04 14:56 UTC, Eduardo-BarrosoS commented on src/app/page.tsx
Develop pixel perfect figma design

2023-12-04 14:56 UTC, Eduardo-BarrosoS commented on src/components/Dialog/Dialog.tsx
> +        </DialogNextUI>
Add max height and an overflow on ModalContent

2023-12-06 13:55 UTC, Eduardo-BarrosoS requested changes
Develop pixel perfect the figma design

2023-12-06 13:55 UTC, Eduardo-BarrosoS commented on src/components/Dialog/index.tsx
> +import { DialogComponent } from "./Dialog";
This file doesn't need to be a .tsx file since there is no TSX code being used in it. Instead, you can use .ts

2023-12-06 16:19 UTC, qalexandre commented
Defina um tamanho máximo para a dialog para que não ocupe toda a tela e deixe o scroll do conteúdo como automático

Depois faça um pull na develop para resolver os conflitos

2023-12-07 15:15 UTC, merged